Добавляет header body footer
htmlacademy-htmlcss/2167205-sedona-36 pull request #2
Opened 2023-01-22 18:19 UTC by Yarilkins

2023-01-22 18:51 UTC, baronin requested changes
- html код не отформатирован
- Нет разметки страницы catalog
- Нет сеции "Приезжайте..."
![image](https://user-images.githubusercontent.com/20131942/213934178-2fe69b8e-fa57-4814-b462-76b9a85da7a8.png)

2023-01-22 18:51 UTC, baronin commented on index.html
> +    <header class="page_header">
Почему все классы через нижнее подчеркивание?

2023-01-22 18:51 UTC, baronin commented on index.html
> +        <img src="#" alt="Welcome">
Это не просто картинка,a полноценная секция, обычно названия им дают hero или intro
![image](https://user-images.githubusercontent.com/20131942/213934033-a9cfb020-a1f1-42b4-9dc5-12b4448a99a6.png)

2023-01-25 13:15 UTC, Yarilkins commented
Исправляет замечания, добавляет секции и меняет нижние подчеркивания на тире

2023-01-25 14:25 UTC, baronin approved these changes

2023-01-25 14:26 UTC, merged

2023-01-31 13:09 UTC, Yarilkins commented on index.html
> +            <p class="newslatter-notation">Только полезная информация и никакого спама, честное бойскаутское!</p>
я так понимаю, что в данной ситуации, в этой секции задний фон будет добавляться не через <img>, а через css-свойство background?