добавляет шрифты и стилизацию
htmlacademy-htmlcss/2167205-sedona-36 pull request #4
Opened 2023-02-10 12:54 UTC by Yarilkins

2023-02-12 18:31 UTC, baronin requested changes
- [ ] Давай переделаем секцию advantages

Вот я скинул пример, какое хотелось бы видеть исполнение
![image](https://user-images.githubusercontent.com/20131942/218326246-9dfa6c48-ac2e-4246-86b3-f6838b37b45f.png)

- [ ] В консоле ошибка, не находит изображение
![image](https://user-images.githubusercontent.com/20131942/218326489-5ee330b9-a156-43d2-9767-17ba8a323fb2.png)

- [ ]

2023-02-12 18:31 UTC, baronin commented on styles/styles.css
> +color: #000000;
не отформатировано

2023-02-12 18:31 UTC, baronin commented on styles/styles.css
> +.navigation-link, .navigation-user-link {
тут свойства одинаковые, давай оставим только .navigation-link

2023-02-12 18:31 UTC, baronin commented on styles/styles.css
> +/*.intro {
закомментированный код

2023-02-12 18:31 UTC, baronin commented on index.html
> +            <button class="button-main button-main-search" type="button">ПОИСК ГОСТИНИЦЫ В седоне</button>
Семейство шрифта не соответствует макету, у тебя Arial , a в макете PT Sans

2023-02-12 18:31 UTC, baronin commented on styles/styles.css
> +  background: #ffffff;
Если только нужен цвет по бекграуну то используй background-color, так же поменяй и в других местах где только используется цвет

2023-02-12 18:31 UTC, baronin commented on index.html
> +          <article class="search-header">
Давай тут article уберем, тут секции search хватат, а если нужен будет контейнер, то добавим див с классом .search-container

2023-02-12 18:31 UTC, baronin commented on index.html
> +            <button class="button-main button-main-search" type="button">ПОИСК ГОСТИНИЦЫ В седоне</button>
Тут больше похоже на ссылку, чем на кнопку

2023-02-13 11:09 UTC, Yarilkins commented
исправляет все замечания из предыдущего коммита

2023-02-13 13:44 UTC, Yarilkins commented
сделал базовую стилизацию

2023-02-19 14:36 UTC, Yarilkins commented
Я отредактировал HTML секцию advantages и попробовал применить стилизацbю к placeholder

2023-02-19 19:44 UTC, merged